Usuarios

### GET ALL USUARIOS
GET http://localhost:8080/api/usuarios

###

### GET USUARIO POR ID
GET http://localhost:8080/api/perfiles

###

### CREATE USUARIO 1
POST http://localhost:8080/api/usuarios/registrar
Content-Type: application/json

{
    "email": "test@uade.edu.ar",
    "contraseña": "password123",
    "nombre": "Juan",
    "apellido": "Perez",
    "dni": "12345678",
    "telefono": "11223344",
    "direccion": "Calle Falsa 123"
}

###

### UPDATE USUARIO
# Replace '1' with the actual user ID
PUT http://localhost:8080/api/usuarios/1
Content-Type: application/json

{
    "nombreUsuario": "evrichtoffen",
    "nombre": "Edward",
    "apellido": "Von Richtoffen",
    "email": "test2@example.com",
    "contraseña": "dfhjsidhfgis3.2"
}

###

### LOGIN
# IMPORTANTE: el campo es "password", no "contraseña"
POST http://localhost:8080/api/usuarios/login
Content-Type: application/json

{
    "email": "test@uade.edu.ar",
    "contraseña": "password123"
}

###

### DELETE USUARIO
DELETE http://localhost:8080/api/usuarios/1

###

